[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "quasigraph"
dynamic = ["version"]
authors = [
  { name="Leandro Seixas Rocha", email="leandro.fisica@gmail.com" },
]
description = "quasigraph: Chemical and Geometric Descriptor Toolkit for Machine Learning Models."
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    'numpy',
    'pandas',
    'ase',
    'mendeleev'
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: Chemistry",
    "Topic :: Scientific/Engineering :: Physics"
]

[project.urls]
"Homepage" = "https://github.com/seixas-research/quasigraph"

[tool.hatch.version]
path = "src/quasigraph/version.py"

